// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlrbAvFeCBq_iDNGIOOFP31YXudGXoK64',
    appId: '1:9240928213:web:1fe92411c3fcd25edc675c',
    messagingSenderId: '9240928213',
    projectId: 'crudcloune',
    authDomain: 'crudcloune.firebaseapp.com',
    storageBucket: 'crudcloune.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJL_tHbbtHF9mH3IhRtmlXWX-Rho7cNxM',
    appId: '1:9240928213:android:76a7ff8eb739d44cdc675c',
    messagingSenderId: '9240928213',
    projectId: 'crudcloune',
    storageBucket: 'crudcloune.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHESYIi-v3UGpimBZ_gHdAClSHIAGbbS8',
    appId: '1:9240928213:ios:1088a342b3a2e1d2dc675c',
    messagingSenderId: '9240928213',
    projectId: 'crudcloune',
    storageBucket: 'crudcloune.appspot.com',
    iosBundleId: 'com.example.crud',
  );
}
